name: CD

permissions: {}

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  cd:
    permissions:
      contents: write
    uses: TerakomariGandesblood/github-workflows/.github/workflows/rust-cd.yml@main
    with:
      bin: file-server
